#!/bin/bash
# Android APK Build Instructions for MazadZoo Mobile App
# Date: December 8, 2025

echo "📱 MazadZoo Android Build Guide"
echo "================================"
echo ""

# Check current environment
echo "Current Environment: GitHub Codespaces"
echo "⚠️  Android SDK is not available in Codespaces"
echo ""

echo "🎯 Build Options Available:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 1: EAS Build (Cloud Build - RECOMMENDED)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This is the easiest way to build your APK without Android SDK."
echo ""
echo "Steps:"
echo "1. Install EAS CLI globally:"
echo "   npm install -g eas-cli"
echo ""
echo "2. Login to your Expo account:"
echo "   eas login"
echo ""
echo "3. Configure EAS Build:"
echo "   eas build:configure"
echo ""
echo "4. Build APK (preview build):"
echo "   eas build --platform android --profile preview"
echo ""
echo "   Or for production:"
echo "   eas build --platform android --profile production"
echo ""
echo "5. Download APK:"
echo "   The build will be available in your Expo dashboard"
echo "   Link will be shown in terminal after build completes"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 2: Local Build (Requires Android SDK)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Prerequisites:"
echo "- Java JDK 17 or higher ✅ (Available)"
echo "- Android SDK ❌ (Not installed in Codespaces)"
echo "- Android Studio (Recommended for SDK)"
echo ""
echo "Steps to build locally (on your local machine):"
echo ""
echo "1. Install Android Studio from:"
echo "   https://developer.android.com/studio"
echo ""
echo "2. Install Android SDK (via Android Studio):"
echo "   - Open Android Studio"
echo "   - Go to Settings > Appearance & Behavior > System Settings > Android SDK"
echo "   - Install Android 13 (API 33) or higher"
echo ""
echo "3. Set ANDROID_HOME environment variable:"
echo "   export ANDROID_HOME=\$HOME/Android/Sdk"
echo "   export PATH=\$PATH:\$ANDROID_HOME/platform-tools"
echo ""
echo "4. Build APK:"
echo "   cd /path/to/mazadzoo/mobile-app/android"
echo "   ./gradlew assembleRelease"
echo ""
echo "5. Find APK at:"
echo "   mobile-app/android/app/build/outputs/apk/release/app-release.apk"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 3: Expo Development Build (For Testing)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "For testing during development (no APK needed):"
echo ""
echo "1. Start Expo dev server:"
echo "   cd mobile-app"
echo "   npx expo start"
echo ""
echo "2. Install Expo Go on your Android phone:"
echo "   https://play.google.com/store/apps/details?id=host.exp.exponent"
echo ""
echo "3. Scan QR code from terminal to test app"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Current Build Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "App Info:"
echo "  Name: Rare Animals Auction"
echo "  Package: com.alkifaa.mazadzoo"
echo "  Version: 1.0.0"
echo ""
echo "Build Profiles (in eas.json):"
echo "  - development: Development build"
echo "  - preview: Preview APK (for testing)"
echo "  - production: Production APK (for release)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Recommended Next Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "For Codespaces Environment:"
echo "  ✅ Use EAS Build (Option 1) - Cloud build service"
echo "  ✅ Or test with Expo Go (Option 3) - No build needed"
echo ""
echo "For Local Machine:"
echo "  ✅ Install Android Studio + SDK"
echo "  ✅ Use local Gradle build (Option 2)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Quick Commands"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "EAS Build (Cloud):"
echo "  npm install -g eas-cli"
echo "  eas login"
echo "  eas build --platform android --profile preview"
echo ""
echo "Expo Go (Testing):"
echo "  cd mobile-app"
echo "  npx expo start"
echo ""
echo "Local Build (Requires Android SDK):"
echo "  cd mobile-app/android"
echo "  ./gradlew assembleRelease"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Recommendation: Use EAS Build for cloud-based building"
echo "   It's free for open source projects and doesn't require SDK setup"
echo ""
echo "📚 Learn more: https://docs.expo.dev/build/setup/"
echo ""
